<?php
include "checklogin.php";
include "header.php";
include "../employee/connection.php";
 ?>
<!--main-container-part-->
<div id="content">
    <!--breadcrumbs-->
    <div id="content-header">
        <div id="breadcrumb"><a href="#" title="Current page" class="tip-bottom"><i class="fas fa-home"></i>
            View Bills</a></div>
    </div>
    <!--End-breadcrumbs-->

    <!--Action boxes-->
    <div class="container-fluid">
          <div class="widget-title"> <span class="icon"><i class="fas fa-book"></i></span>
            <h5>View Bills</h5>
          </div>

          <div class="row-fluid" style="background-color: white; min-height: 1000px; padding:10px;">
          <div class="span12">

            <div class="widget-box">
              <div class="widget-content padding">
            <form class="form-inline" action="" name="form1" method="post">
                      <br>
                       <div class="form-group">
                           <label for="email">Select Start Date</label>
                           <input type="date" id="date_start" name="date_start" placeholder="YYYY-MM-DD" value="<?php echo date("Y-m-d") ?>">
                       </div>
                       <br>
                       <div class="form-group">
                           <label for="email">Select End Date</label>
                            <input type="date" id="date_end" name="date_end" placeholder="YYYY-MM-DD" value="<?php echo date("Y-m-d") ?>">
                       </div>
                       <br>
                       <button type="submit" name="submitStart" class="btn btn-success">Show Purchase From These Dates</button>
                       <button type="button" name="submitEnd" class="btn btn-warning" onclick="window.location.href=window.location.href">Clear Search</button>
                   </form>

                   <br>
                  </div>
                </div>

        <div class="widget-box">

          <div class="widget-content nopadding">
            <table class="table table-bordered">
              <tr>
                <th>Bill number</th>
                <th>Bill Generated by</th>
                <th>Phone Number</th>
                <th>Payment Method</th>
                <th>Billing Date</th>
                <th>Bill Total</th>
                <th>View Details</th>
              </tr>

              <?php
              if(isset($_POST["submitStart"]))
              {
                $res = mysqli_query($link,"select * from billing_header where date>= '$_POST[date_start]' && date<='$_POST[date_end]'");
              }
              else
              {
                $res = mysqli_query($link,"select * from billing_header order by id desc");
              }
               
               while($row = mysqli_fetch_array($res))
               {
                 echo "<tr>";
                 echo "<td>"; echo $row["bill_no"]; echo "</td>";
                 echo "<td>"; echo $row["username"]; echo "</td>";
                 echo "<td>"; echo $row["phno"]; echo "</td>";
                 echo "<td>"; echo $row["payment_method"]; echo "</td>";
                 echo "<td>"; echo $row["date"]; echo "</td>";
                 echo "<td>";  echo "₹".get_total($row["id"],$link); echo "</td>";
                 echo "<td>";?><a href="view_bill_details.php?id=<?php echo $row["id"];?>" style="color:#11C2A3" > View Details </a> <?php echo "</td>";
                 echo "</tr>";
               }
               ?>
            </table>
        </div>
      </div>
    </div>
</div>

<!--end-main-container-part-->

<?php

function get_total($bill_id, $link)
{
  $total=0;
  $res2=mysqli_query($link, "select * from billing_details where bill_id = '$bill_id'");
  while ($row=mysqli_fetch_array($res2))
  {
    $total = $total+($row["price"]*$row["qty"]);
  }
  return $total;
}

 ?>


<?php
include "footer.php";
 ?>
